### ISSUE TITLE
General numbers as date

### ISSUE THREAD

**Issue by tsamu** [shuchkin/simplexls#1]
If you create an xls in openoffice, general numbers parsed as date (yyyy-mm-dd hh:mm:ss). If you set cell type: number -1234 it works as expected.

**Comment by tsamu** [comment]
[sample.xls.zip](https://github.com/shuchkin/simplexls/files/2876819/sample.xls.zip)

**Comment by shuchkin** [comment]
try 0.9.3
https://github.com/shuchkin/simplexls

**Comment by tsamu** [comment]
It seems ok now! Thanx.
