### ISSUE TITLE
Error in parsing UTF-8 

### ISSUE THREAD

**Issue by GUSTAVPEREIRA** [shuchkin/simplexls#10]
Please you can help me, i try using 
`header('Content-Type: text/html; charset=utf-8'); 
$lines = \SimpleXLS::parse($filepath);
`

But this characters don't convert "Ibirité" -> "Ibirit�".
You can help me. and sorry for bad english i'am learning now.

**Comment by dasperg** [comment]
Hi, i have same issue.
Some cells have right format/encoding, but some not. 
```
[3] => kábel
[4] => k�bel
```
Second `[4]` is the same word `kábel`.
I was trying:
```
$this->xls->setColumnFormat(4, '');
# OR
$this->xls->setColumnFormat(4, SimpleXLS::TYPE_LABEL);
# OR
$this->xls->setColumnFormat(4, SimpleXLS::TYPE_NAME);
```
Of course, with `header('Content-Type: text/html; charset=utf-8');`

**Comment by shuchkin** [comment]
please, attach XLS

**Comment by GUSTAVPEREIRA** [comment]
[dados3 (1).zip](https://github.com/shuchkin/simplexls/files/6084093/dados3.1.zip)

**Comment by GUSTAVPEREIRA** [comment]
I send in .zip because github don't suport xls, in file attached.

**Comment by GUSTAVPEREIRA** [comment]
[dados3.zip](https://github.com/shuchkin/simplexls/files/6084099/dados3.zip)

I send in .zip because github don't suport xls, in file attached.

**Comment by GUSTAVPEREIRA** [comment]
I think no i send Planilha Microsoft Excel 97-2003 (.xls), using xls

**Comment by shuchkin** [comment]
not xlsx, there ods

**Comment by GUSTAVPEREIRA** [comment]
[dados3_1.zip](https://github.com/shuchkin/simplexls/files/6084477/dados3_1.zip)
Ok i send again, please check this

**Comment by shuchkin** [comment]
try 0.9.9
$xls->toHTML();
I have this table
<img width="1348" alt="Screenshot_444" src="https://user-images.githubusercontent.com/315872/109983476-0d980900-7d2d-11eb-8d0d-84f194a0c71f.png">

**Comment by GUSTAVPEREIRA** [comment]
I will try one minut

**Comment by dasperg** [comment]
I have updated to version `0.9.9` from `0.9.6`.
```
ini_set('error_reporting', E_ALL );
ini_set('display_errors', 1 );
//        header('Content-Type: text/html; charset=utf-8');
$xls = SimpleXLS::parse($path, false, true));
$xls->success(); // true
```
- `$xls->toHTML();` missing/empty values
- `$xls->rows();`  same result

My file: [X_Zoznam spojov.xls.zip](https://github.com/shuchkin/simplexls/files/6085100/X_Zoznam.spojov.xls.zip)

`mbstring` installed
```
root@ff287cd2b12e:/var/www/html# locale 
LANG=sk_SK.utf8
LANGUAGE=sk_SK:sk
LC_CTYPE="sk_SK.utf8"
LC_NUMERIC="sk_SK.utf8"
LC_TIME="sk_SK.utf8"
LC_COLLATE="sk_SK.utf8"
LC_MONETARY="sk_SK.utf8"
LC_MESSAGES="sk_SK.utf8"
LC_PAPER="sk_SK.utf8"
LC_NAME="sk_SK.utf8"
LC_ADDRESS="sk_SK.utf8"
LC_TELEPHONE="sk_SK.utf8"
LC_MEASUREMENT="sk_SK.utf8"
LC_IDENTIFICATION="sk_SK.utf8"
LC_ALL=sk_SK.utf8
```
Environment: docker `FROM php:5.6.40-apache-jessie`

**Comment by GUSTAVPEREIRA** [comment]
[dados3_1.zip](https://github.com/shuchkin/simplexls/files/6085380/dados3_1.zip)
I change version 0.9.6 to 0.9.9 also, but doesn't,  yet import occurring same error, please you have other suggestion?

In word Ibereté line 32 in my file.

**Comment by GUSTAVPEREIRA** [comment]
> try 0.9.9
> $xls->toHTML();
> I have this table
> <img alt="Screenshot_444" width="1348" src="https://user-images.githubusercontent.com/315872/109983476-0d980900-7d2d-11eb-8d0d-84f194a0c71f.png">

Iberet doesn't according stay without É in iberet, sorry again for bad english.

**Comment by shuchkin** [comment]
in my excel 
<img width="1248" alt="Screenshot_449" src="https://user-images.githubusercontent.com/315872/110002495-a5065780-7d3f-11eb-9772-45bdd7bd3030.png">

**Comment by shuchkin** [comment]
zoznam
<img width="1507" alt="Screenshot_448" src="https://user-images.githubusercontent.com/315872/110002595-be0f0880-7d3f-11eb-8f08-0ad4aeef78bc.png">

try setlocale(LC_ALL, "en_US.UTF-8");

**Comment by GUSTAVPEREIRA** [comment]
I Try using setlocale(LC_ALL, "en_US.UTF-8");

My file using $file->toHTML();
![image](https://user-images.githubusercontent.com/17938215/110004213-effb7d00-7cf5-11eb-888f-50a1e93a16b3.png)

How you can see, this part is in blank, but in my file contains "ibireté"
![image](https://user-images.githubusercontent.com/17938215/110004262-01448980-7cf6-11eb-99d9-cfff201ff268.png)

**Comment by shuchkin** [comment]
may be you lost "é" when export table?

**Comment by GUSTAVPEREIRA** [comment]
Sorry i don't understand, you can explain ?

**Comment by shuchkin** [comment]
please open your xls in Excel

**Comment by GUSTAVPEREIRA** [comment]
I Can open in online excel ?

**Comment by shuchkin** [comment]
any other reader

**Comment by GUSTAVPEREIRA** [comment]
I open in libreoffice
![image](https://user-images.githubusercontent.com/17938215/110045138-0242de80-7d29-11eb-8d02-6ba72ae6c524.png)
Please open last zip, that i send to you.
[dados3_1.zip](https://github.com/shuchkin/simplexls/files/6087203/dados3_1.zip)

**Comment by pvalin** [comment]
Hi,

I encountered the problem and I found a solution.

A cell where we have a character with an acute (éèà...) but any other special characters (like "œ" or "ø"), Excel registred the cell in ISO-8859-1 instead of UTF-8, don't ask me why.

So, if I insert the php function utf8_encode(), it works fine.

See pull request https://github.com/shuchkin/simplexls/pull/18

**Comment by shuchkin** [comment]
> Excel registred the cell in ISO-8859-1 instead of UTF-8, don't ask me why.

plz open xlsx with 7z or other ZIP reader,
there UTF-8 in sharedStrings.xml ?
<img width="797" alt="Screenshot_10" src="https://user-images.githubusercontent.com/315872/133987564-ae690da5-ceba-4548-b511-78e0719fa2e0.png">

**Comment by pvalin** [comment]
We speak about SimpleXLS, not SimpleXLSX.

I speak at the cell level, not the document.
A cell with "à	á	â	ã	ä	å	æ	ç	è	é	ê	ë	ì	í	î	ï	ð	ñ	ò	ó	ô	õ	ö	ø	œ	š	Þ	ù	ú	û	ü	ý	ÿ" -> UTF-8
A cell with just "é" -> ISO-8859-1

I don't know why. The issue appeared in march 2021, maybe an update of Excel who converts XLSX to XLS in a different way? (In reality, I ask me if manage XLS file in 2021 is useless :D)

**Comment by shuchkin** [comment]
> We speak about SimpleXLS, not SimpleXLSX.

my bad

Try 0.9.12
thx [Nil-av](https://github.com/Nil-av)  for persistence

Excel used UTF18LE or Latin-1
Latin1 0..127 === UTF8, BUT(!) Latin1 128..255 !== UTF8 ( because 2 bytes/chars used there )

**Comment by pvalin** [comment]
Yes it works ! I will test many files in the nexts weeks, I keep you in touch.
