### ISSUE TITLE
XLS not recognized

### ISSUE THREAD

**Issue by LeandroLavra** [shuchkin/simplexls#13]
Could you help me? I have a xls file that was generated in a restaurant system with the daily transactions. In Excel 365 this file opens in Compatible Mode. But, In the SimpleXLS it gives "File is not XLS" message.

It seems the problem was in ole identification, but my knowledge is not so deep to solve it... :)
File could be reached at link: 
[Xls file](http://www.vanessalavra.com.br/Excel/TestFile.xls) 

Tks for your help.

**Comment by shuchkin** [comment]
Xls file - 404 Not Found

**Comment by LeandroLavra** [comment]
Sorry. The file is attached.

Em sáb, 27 de mar de 2021 14:17, Sergey Shuchkin ***@***.***>
escreveu:

**Comment by shuchkin** [comment]
no attachment
<img width="727" alt="Screenshot_500" src="https://user-images.githubusercontent.com/315872/112749130-35078c00-8fe2-11eb-8ac5-ad3445189e1e.png">

use github
<img width="707" alt="Screenshot_501" src="https://user-images.githubusercontent.com/315872/112749133-38027c80-8fe2-11eb-8236-99899e651b92.png">

**Comment by LeandroLavra** [comment]
Sending again in zip format. :-)

[TestFile.zip](https://github.com/shuchkin/simplexls/files/6217607/TestFile.zip)

**Comment by shuchkin** [comment]
Unknown file signature

<img width="437" alt="Screenshot_503" src="https://user-images.githubusercontent.com/315872/112842712-ab2fef80-90c3-11eb-9eee-2ed200630f08.png">

What softwareг u use to generate this file?

**Comment by LeandroLavra** [comment]
Thanks for your help.  :-)
I received the file from a restaurant management system that export the reports to this "excel format".
Do you think it is possible to adapt your php class to read this file? Because the file opens without problems in Excel.
How can I make this file signature accepted in your class?

**Comment by shuchkin** [comment]
¯\\_(ツ)_/¯

**Comment by LeandroLavra** [comment]
I gave up to read this file using PHP... had to change to C# using an .NET package. Tks for your help! :-)
