### ISSUE TITLE
Document reading bug

### ISSUE THREAD

**Issue by brayaninteriano** [shuchkin/simplexls#15]
When I upload the xls file, the text in the rows and columns is always cut off the last character and the text is incomplete.

**Comment by brayaninteriano** [comment]
![Captura](https://user-images.githubusercontent.com/71684839/129385872-77134498-e44a-470e-9634-60cfb1afd786.PNG)

**Comment by shuchkin** [comment]
Send me your xls to ***@***.***

пт, 13 авг. 2021 г., 22:53 brayaninteriano ***@***.***>:

**Comment by shuchkin** [comment]
how did you fix it?
