### ISSUE TITLE
Improvement: get state of a sheet

### ISSUE THREAD

**Issue by pvalin** [shuchkin/simplexls#19]
In SimpleXLSX, I added the possibility to have the state of a sheet (hidden or not) and others attributes: 
`foreach ( $workbook->sheets->sheet as $s ) {
						$this->sheetNames[ $index ]  = (string) $s['name'];
						$this->sheetAttributes[ $index ] = [
							'name' => (string) $s['name'],
							'sheetId' => (string) $s['sheetId'],
							'id' => (string) $s['id'],
							'state' => (string) $s['state']
						]; //added line
						$index_rId[ $index ]         = (string) $s['id'];
						$index ++;
					}`

And
`public function sheetAttributes() { 
		return $this->sheetAttributes;
	}`

I want to ignore hidden tabs during my reading file because if the user decided to hidden it, it's voluntary.

With SimpleXLS, it's possible too but I am not a BIFF expert. With the Hexinator application, I found that the information is in before the tab name.

Example: 
00 00 **00** 00 05 00 _54 61 62 20 31_ 85 00 0D 00 9E 43 00 00 **01** 00 05 00 _54 61 62 20 32_ 85 00 0D 00 54 45 00 00 **01** 00 05 00 _54 61 62 20 33_ 85 00 0D 00 0A 47 00 00 **00** 00 05 00 _54 61 62 20 34_
The tabs are named "Tab 1" (visible), "Tab 2" (hidden), "Tab 3" (hidden) and "Tab 4" (visible) -> 54 61 62 20 ## (according to the number)
In bold, you have the hex who indicates if hidden (01) or not (00).

In your code, we can easely push the information here (Line ~800): 
`$this->boundsheets[] = array(
						'name'   => $rec_name,
						'offset' => $rec_offset,`
adding 'hidden' => 0/1

I found the right position for BIFF8 / charset === 0 who is "ord($this->data[ $pos + 8])", I suppose it's the same for any chartype but I don't know how to test. And I don't know for BIFF7 (I see it's for document before year 2000, impossible to generate a new one no?).

Thanks for your help

**Comment by pvalin** [comment]
With an old, old, old computer, I succeeded to create an Excel 2003 (BIFF8) and an Excel 1995 (BIFF7)!

In the two cases, it was impossible to hide a sheet (only row or column). Game Over. No need to check for BIFF7 case.

**Comment by shuchkin** [comment]
try 0.9.13

**Comment by pvalin** [comment]
It works like a charm! Thanks.
