### ISSUE TITLE
Find Active sheet?

### ISSUE THREAD

**Issue by mostafa-norouzi** [shuchkin/simplexls#21]
Hi, and thank you for this light reader.
I have a problem  (spent one day no clue) :

**I need to find active sheet** 
In simpleXLSX I found it with a tiny modification but in simpleXLS (because source is binary) I don't succeed yet.

Is there any guid to catch the **tabId**?
Any help would be appreciated.

**Comment by shuchkin** [comment]
try 0.9.15
see [examples](https://github.com/shuchkin/simplexls#sheet-names)

**Comment by mostafa-norouzi** [comment]
You saved me. it's working like a charm.
