### ISSUE TITLE
Number is transformed into an exponential number

### ISSUE THREAD

**Issue by isckraa** [shuchkin/simplexls#23]
Hi there, 

I have a problem when I try to read my "XLS" file and more specifically on the column that contains this value **"202906789123456"**.

The problem is that this value is transformed into an **exponential number** and the value I get when retrieving the data is as follows: **"2.0290678912346E+14"**.

How can I block the cast?

Thanks.

**Comment by shuchkin** [comment]
(int) $cell works?

**Comment by isckraa** [comment]
If i try to cast **"2.0290678912346E+14"** to int I get this **202906789123460**.

**Comment by shuchkin** [comment]
https://www.php.net/manual/en/ini.core.php#ini.precision

**Comment by isckraa** [comment]
Thanks a lot.
