### ISSUE TITLE
Problem with the maximum range of the 64k loop - warning

### ISSUE THREAD

**Issue by mariuszkoncewicziip** [shuchkin/simplexls#25]
Line 527 - PHP print warnings, when row is empty

I suggest a change:

before:
$name .= $d[ $i ];

after:
if (isset($d[ $i ])) { $name .= $d[ $i ]; }

**Comment by shuchkin** [comment]
send me XLS file

**Comment by shuchkin** [comment]
sergey.shuchkin@gmail.com

**Comment by mariuszkoncewicziip** [comment]
There is a problem. I have a confidential file, and after changing the data and saving it as ... Excel 97/2003 the problem disappears.

**Comment by shuchkin** [comment]
fix your current version, and stop update by composer

**Comment by shuchkin** [comment]
if there are requests with similar problems from other users, then I will fix the master branch
