### ISSUE TITLE
Formula evaluation - incorrect percent result

### ISSUE THREAD

**Issue by ConnectGrid** [shuchkin/simplexls#27]
Got an XLS spreadsheet where a simple formula (`=F19/$F$22`) shows 100.00% correctly in Excel, but results in 1.00% after parsing with this library.

I've reviewed the code line-by-line, but can't see where or how formulas are evaluated. (Major respect for those of you that understand what's happening inside of XLS files!)

Does this library do actual formula evaluation, or are formula results stored in the XLS data and simply read by this library?

**Comment by shuchkin** [comment]
fixed in 0.10.2

(there precalculated values)

**Comment by ConnectGrid** [comment]
Thank you so much for the super-fast response! This is the only library that I can get to parse XLS files, so your quick fix is a lifesaver for my project. 🤗
