### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by ro0NL** [shuchkin/simplexls#38]
would be nice to have 1.x stable

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable. (https://semver.org/)

**Comment by ro0NL** [comment]
cc @shuchkin

**Comment by ro0NL** [comment]
cc @shuchkin

**Comment by shuchkin** [comment]
There binary format and and I'm not sure that development is actively continuing, it's very difficult to write new things that users are asking for.

major bugs or security fixing only

**Comment by ro0NL** [comment]
i would tag the status quo (master branch) as 1.0.0 regardless

but OK, no active development is another concern.

**Comment by shuchkin** [comment]
https://github.com/shuchkin/simplexls/tags

**Comment by ro0NL** [comment]
@shuchkin 💯 the goal to me is having semver-compat deps/releases, generally
