### ISSUE TITLE
Character problem

### ISSUE THREAD

**Issue by durmusun** [shuchkin/simplexls#4]
Whenever there is a Turkish character in any cell it converts it to a question mark. Specifically, in the reading of "Ü,ü,Ö,ö” characters problem arises.

**Comment by shuchkin** [comment]
try set page charset before output
header('Content-Type: text/html; charset=utf-8');
$xls = SimpleXLSX::parse....

**Comment by memo20yorga** [comment]
I have the same issue. Some of the some türkish charachters  "Ü,ü,Ö,ö" sometimes are read wrong. In the same cell when I change cell context it is read one time wrong one time right. interesting issue.

**Comment by shuchkin** [comment]
class works good with unicode,  just don't forget set output charset:

`header('Content-Type: text/html; charset=utf-8');`

one time wrong one time right --- so browser charset autodetection not perfect without this header

**Comment by memo20yorga** [comment]
Thanks for your reply. I expressed myself wrong. sorry about my english. I'm trying to import excel file which includes turkhish characters. I read excel file and record them to the database with code shown below.
If you think it is appropriate I can send you my excel file which I made my trials

            header('Content-Type: text/html; charset=utf-8');
            $xls = new SimpleXLS($excelFilePath);
            $headers = $rows = [];
            //echo "<pre>";
            if ($xls->success()) {

                print_r($xls->rows());
                foreach ($xls->rows() as $k => $r) {
                    if ($k === 0) {
                        $headers = $r;
                        continue;
                    }else{
                        if($r[0]!=""){
                            $katilimci_bulk = new FuarKatilimci();
                            $katilimci_bulk->setFirmaAdi($r[0]);
                            $katilimci_bulk->setHolNo($r[1]);
                            $katilimci_bulk->setStantNo($r[2]);
                            $katilimci_bulk->setYetkili($r[3]);
                            $katilimci_bulk->setMail($r[4]);
                            $katilimci_bulk->setTelefon($r[5]);
                            $katilimci_bulk->setFax($r[6]);
                            $katilimci_bulk->setAdres($r[7]);
                            $katilimci_bulk->setSehir($r[8]);
                            $katilimci_bulk->setUrunGrubu($r[9]);
                            $katilimci_bulk->setFuar($entity->getFuar());


                            $em->persist($katilimci_bulk);
                            $em->flush();
                        }
                    }
                }

**Comment by shuchkin** [comment]
> If you think it is appropriate I can send you my excel file which I made my trials

no, thx, have nice day )
