### ISSUE TITLE
Library breaks when user uploads file with Norwegian characters

### ISSUE THREAD

**Issue by chigozieorunta** [shuchkin/simplexls#8]
I noticed that the page breaks when you try to upload a file with Norwegian characters, could this be as a result of the character encoding? Is there a solution or work around for this?

![Screen Shot 2020-12-01 at 6 41 20 AM](https://user-images.githubusercontent.com/11831265/100701863-c18d9f00-33a0-11eb-89be-fbb5db7e6206.png)

**Comment by shuchkin** [comment]
try set page charset before output
```
header('Content-Type: text/html; charset=utf-8');
$xls = SimpleXLSX::parse....
```
<img width="417" alt="Screenshot_272" src="https://user-images.githubusercontent.com/315872/100763494-6a7adf00-341f-11eb-8ec0-e83a85902b33.png">

**Comment by chigozieorunta** [comment]
Hi Sergey,

Thanks a lot. I really appreciate.
