### ISSUE TITLE
datetime field not parsed correctly

### ISSUE THREAD

**Issue by bogdanvursu** [shuchkin/simplexls#9]
The date time field in my Excel file is not parsed correctly. Could you please take a look at my file?
I only parsed the file contents ($file_data is the actual contents of the file, not the path) and printed the rows.

$xls = SimpleXLS::parse($file_data, TRUE));
print_r($xls->rows());

[header_one_line_twitter.xls.zip](https://github.com/shuchkin/simplexls/files/5971523/header_one_line_twitter.xls.zip)

**Comment by shuchkin** [comment]
try 0.9.8

**Comment by cbodis** [comment]
Hi, I have a similar issue. The format in my excel is '2021.10.21' -> 'YYYY.MM.DD' and upon parsin with SimpleXLS it gets translated into value '44439'.

**Comment by shuchkin** [comment]
> Hi, I have a similar issue. The format in my excel is '2021.10.21' -> 'YYYY.MM.DD' and upon parsin with SimpleXLS it gets translated into value '44439'.

actual version?

**Comment by cbodis** [comment]
> > Hi, I have a similar issue. The format in my excel is '2021.10.21' -> 'YYYY.MM.DD' and upon parsin with SimpleXLS it gets translated into value '44439'.
> 
> actual version?

Yes, latest one. Not a big issue as I found a workaround by translating "exceltime" into unix time.
```
$UNIX_DATE = ($excel_date_ value - 25569) * 86400;
$mydate = gmdate("Y-m-d", $UNIX_DATE);
```

**Comment by shuchkin** [comment]
pls send me xlsx
just there YYYY-MM-DD HH:MM:SS used as default

see helpers
https://github.com/shuchkin/simplexlsx#datetime-helpers

**Comment by shuchkin** [comment]
send me xls

**Comment by cbodis** [comment]
> send me xls

Data sanitized.
[sample.xls](https://github.com/shuchkin/simplexls/files/7468620/sample.xls)

**Comment by shuchkin** [comment]
try 0.9.14
